name: Profile 3D Contributions

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours (safe)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: prosonjit2006

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update 3d contributions" || echo "no changes"
          git push
