name: Profile 3D Contributions

on:
  schedule:
    - cron: "59 11 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: prosonjit2006

      - name: Debug files
        run: ls -R

      - name: Commit & Push Changes
        run: |
          git config user.name "prosonjit2006"
          git config user.email "prosonjitdatta2006@gmail.com"
          git add -A .
          git commit -m "update 3d contributions" || echo "no changes"
          git push
